language: python

python: 2.7

sudo: false
cache:
    directories: [$HOME/.cache/pip]

install: pip install -r _build/.requirements.txt

script: make -C _build SPHINXOPTS=-nW html

branches:
    except:
        - github-comments

.. ready: no
.. revision: 90535a14b63324c344b52d99d5e597bda5696792