block_name
~~~~~~~~~~

**type**: ``string`` **default**: the form's name (see :ref:`Knowing which
block to customize <form-customization-sidebar>`)

Allows you to override the block name used to render the form type.
Useful for example if you have multiple instances of the same form and you
need to personalize the rendering of the forms individually.

.. ready: no
.. revision: ca035f080e88e886ec221c515be72c261b4d25ac