block_prefix
~~~~~~~~~~~~

**type**: ``string`` or ``null`` **default**: ``null`` (see :ref:`Knowing which
block to customize <form-customization-sidebar>`)

Allows you to add a custom block prefix and override the block name
used to render the form type. Useful for example if you have multiple
instances of the same form and you need to personalize the rendering
of all of them without the need to create a new form type.

.. ready: no
.. revision: bcc55c55a68ab728fe56730fbc7d044bdf557fee