html5
~~~~~

**type**: ``boolean`` **default**: ``true``

If this is set to ``true`` (the default), it'll use the HTML5 type (date, time
or datetime) to render the field. When set to ``false``, it'll use the text type.

This is useful when you want to use a custom JavaScript datepicker, which
often requires a text type instead of an HTML5 type.

.. ready: no
.. revision: da51bc4f40f35718e3e9b21783979e04d81fc078