Select Tag, Checkboxes or Radio Buttons
---------------------------------------

This field may be rendered as one of several HTML fields, depending
on the ``expanded`` and ``multiple`` options:

========================================  =========  =========
Element Type                              Expanded   Multiple
========================================  =========  =========
select tag                                ``false``  ``false``
select tag (with ``multiple`` attribute)  ``false``  ``true``
radio buttons                             ``true``   ``false``
checkboxes                                ``true``   ``true``
========================================  =========  =========

.. ready: no
.. revision: 97f4eebf06cffad93f9084a83f44050f6624518b