translation_domain
~~~~~~~~~~~~~~~~~~

**type**: ``string``, ``null`` or ``false``  **default**: ``null``

This is the translation domain that will be used for any label or option
that is rendered for this field. Use ``null`` to reuse the translation domain
of the parent form (or the default domain of the translator for the root
form). Use ``false`` to disable translations.

.. ready: no
.. revision: 5905e69d9a70925e36e933125544e8dd1cce1454