https://{default}/:
  cache:
    cookies:
      - '*'
    default_ttl: 0
    enabled: true
    headers:
      - Accept
      - Accept-Language
  type: upstream
  upstream: symfonydocs:http

.. ready: no
.. revision: 84249f9849c2b785721abf60dbc3cc489d6ebfcb