propertyPath
~~~~~~~~~~~~

**type**: ``string``

It defines the object property whose value is used to make the comparison.

For example, if you want to compare the ``$endDate`` property of some object
with regard to the ``$startDate`` property of the same object, use
``propertyPath="startDate"`` in the comparison constraint of ``$endDate``.

.. ready: no
.. revision: f856772c4cd79e4e38df415efd342853eb522575