on: [push, pull_request]
name: Lint
jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst
              with:
                  args: --short

.. ready: no
.. revision: b6d2bd0406e24d979af08bc7d5726666af65b688